config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :courses
  root "courses#index"

  get '/about', to: "pages#about"
  get '/help', to: "pages#help"
  get '/contact_us', to: "pages#contact"
  get '/courses/new', to: "courses#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def new

  end

  private

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

  def help

  end

  def contact

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.haml
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @course.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :short_name
    = f.text_field :short_name
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
.row
  .col.s12
    %h3.center-align Course Listing
.row
  - if @courses.blank?
    .col.s6.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          %span.card-title No Courses Available At This Time
        .card-action
          = link_to "Create Course", course_new_path, class: ""
  - else
    - @courses.each do |course|
      .col.s6.m6
        .card.blue-grey.darken-1
          .card-content.white-text
            %span.card-title= "#{course.short_name}: #{course.name}"
            %p= course.description
          .card-action
            = link_to "Enroll", "#", class: ""
            = link_to "Info", "#", class: ""

app/views/courses/new.html.haml
%h3 New courses

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Short name:
  = @course.short_name
%p
  %b Name:
  = @course.name
%p
  %b Description:
  = @course.description

= link_to 'Edit', edit_course_path(@course)
\|
= link_to 'Back', courses_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tech University
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %ul#account1.dropdown-content
        %li
          %a{:href => "#!"} one
        %li
          %a{:href => "#!"} two
        %li.divider
        %li
          %a{:href => "#!"} three
      %ul#account2.dropdown-content
        %li
          %a{:href => "#!"} one
        %li
          %a{:href => "#!"} two
        %li.divider
        %li
          %a{:href => "#!"} three

      %nav
        .container
          .nav-wrapper
            = link_to root_path, class: "brand-logo right" do
              Tech University
            = link_to "#", data: { target: 'mobile-demo' }, class: "sidenav-trigger" do
              %i.material-icons menu

            %ul#nav-mobile.left.hide-on-med-and-down
              %li
                = link_to "Courses", "#!"
              %li
                = link_to "Enrollments", "#!"
              %li
                = link_to "#!", data: { target: "account1" }, class: "dropdown-trigger" do
                  Account
                  %i.material-icons.right arrow_drop_down
            %ul#mobile-demo.sidenav
              %li
                = link_to "Courses", "#!"
              %li
                = link_to "Enrollments", "#!"
              %li
                = link_to "#!", data: { target: "account2" }, class: "dropdown-trigger" do
                  Account
                  %i.material-icons.right arrow_drop_down


    %main
      .container
        = yield

    %footer.page-footer
      .container
        .row
          .col.l6.s12
            %h5.white-text Tech University
            %p.grey-text.text-lighten-4 The future of development training
          .col.l4.offset-l2.s12
            %h5.white-text Information
            %ul
              %li
                = link_to help_path, class: "grey-text text-lighten-3" do
                  Help
              %li
                = link_to about_path, class: "grey-text text-lighten-3" do
                  About
              %li
                = link_to contact_us_path, class: "grey-text text-lighten-3" do
                  Contact Us
      .footer-copyright
        .container
          &copy;
          = "#{Time.now.year} Copyright Text"
          %a.grey-text.text-lighten-4.right{:href => "#!"} More Links

app/views/pages/about.html.haml
%h3 This is the about page

app/views/pages/contact.html.haml
%h3 This is the contact us page

app/views/pages/help.html.haml
%h3 This is the help page

app/views/students/_form.html.haml
= form_for @student do |f|
  - if @student.errors.any?
    #error_explanation
      %h2= "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      %ul
        - @student.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Password
      %th
      %th
      %th

  %tbody
    - @students.each do |student|
      %tr
        %td= student.name
        %td= student.email
        %td= student.password
        %td= link_to 'Show', student
        %td= link_to 'Edit', edit_student_path(student)
        %td= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', students_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @student.name
%p
  %b Email:
  = @student.email
%p
  %b Password:
  = @student.password

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path